#!/usr/bin/env node
// Explicit maintainer build. Consumers install only the reviewed archive.
import {mkdirSync,readFileSync,writeFileSync,copyFileSync,existsSync,readdirSync,rmSync} from 'node:fs';
import {resolve,join,basename} from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {nativeSourceIdentity} from './source-identity.mjs';
const root=resolve(import.meta.dirname,'..'),mac=process.platform==='darwin',arch=process.arch;
if(!(mac&&arch==='arm64'||process.platform==='linux'&&['arm64','x64'].includes(arch)))throw Error('Unsupported maintainer target');
const triple=mac?'aarch64-apple-darwin':(arch==='arm64'?'aarch64':'x86_64')+'-unknown-linux-gnu',id=mac?'macos-arm64':'linux-'+arch;
const cache=join(root,'.aug-build',mac?'native':'native-linux-'+arch),out=join(cache,'artifact');mkdirSync(cache,{recursive:true});rmSync(out,{recursive:true,force:true});for(const folder of ['lib','licenses'])mkdirSync(join(out,folder),{recursive:true});
const manifest=JSON.parse(readFileSync(join(root,'aug-package.json'))),lock=JSON.parse(readFileSync(join(root,'native/sources.lock.json')));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const cc=process.env.AUG_CC??(mac?'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang':'clang');
const sdk=process.env.SDKROOT??'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk';
const flags=['-O2','-fPIC','-ffile-prefix-map='+root+'=/aug-native/aug-postgres',...(mac?['-isysroot',sdk,'-mmacosx-version-min=14.0']:arch==='arm64'?['-march=armv8-a']:['-march=x86-64','-mtune=generic'])];
const run=(command,args,options={})=>{const result=spawnSync(command,args,{cwd:root,encoding:'utf8',maxBuffer:30000000,...options});if(result.status!==0)throw Error(command+': '+(result.stderr||result.stdout||result.error?.message).slice(-5000));return result.stdout;};
for(const input of lock.inputs){const file=join(cache,input.name+'.tar');if(!existsSync(file)){const response=await fetch(input.url,{signal:AbortSignal.timeout(180000)});if(!response.ok)throw Error('Missing pinned source '+input.url);const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>100000000||sha(bytes)!==input.sha256)throw Error('Upstream archive digest/size differs');writeFileSync(file,bytes);}if(sha(readFileSync(file))!==input.sha256)throw Error('Cached source digest differs');const directory=input.name==='openssl'?'openssl-3.5.9':'postgresql-18.6';rmSync(join(cache,directory),{recursive:true,force:true});run('tar',['-xf',file,'-C',cache]);}
const tls=join(cache,'tls'),openssl=join(cache,'openssl-3.5.9'),pg=join(cache,'postgresql-18.6'),build=join(cache,'postgres-build');for(const path of [tls,build])rmSync(path,{recursive:true,force:true});mkdirSync(build,{recursive:true});
const env={...process.env,CC:cc,CFLAGS:flags.join(' '),LDFLAGS:(mac?'-isysroot '+sdk+' -mmacosx-version-min=14.0':'')};
if(!existsSync(join(tls,'lib/libssl.a'))){run('perl',['Configure',mac?'darwin64-arm64-cc':arch==='arm64'?'linux-aarch64':'linux-x86_64','no-shared','no-pinshared','no-dso','no-module','--libdir=lib','--prefix='+tls],{cwd:openssl,env});run('make',['-j4','build_libs'],{cwd:openssl,env});run('make',['install_dev'],{cwd:openssl,env});}
if(!existsSync(join(build,'Makefile'))){run(join(pg,'configure'),['--prefix='+join(cache,'pg-install'),'--with-ssl=openssl','--with-includes='+join(tls,'include'),'--with-libraries='+join(tls,'lib'),'--without-icu','--without-readline','--without-zlib','--without-gssapi','--without-ldap','--without-libcurl','--without-libxml','--without-libxslt','--without-lz4','--without-zstd','--disable-nls'],{cwd:build,env});}
// Build the static interface, not libpq's dynamic exit-symbol check. That check
// also sees OpenSSL's registered process cleanup when linked statically.
run('make',['-j4','-C','src/interfaces/libpq','libpq.a'],{cwd:build,env});
run('make',['-j4','-C','src/common','libpgcommon_shlib.a'],{cwd:build,env});run('make',['-j4','-C','src/port','libpgport_shlib.a'],{cwd:build,env});
const library='lib/libaug_postgres'+(mac?'.1.dylib':'.so.1'),target=join(out,library);
const exports=join(cache,'exports');const header=readFileSync(join(root,'native/include/aug_postgres.h'),'utf8'),symbols=[...header.matchAll(/AUG_EXPORT\s+\w+\s+(aug_postgres_\w+)\(/g)].map(match=>match[1]);
writeFileSync(exports,mac?symbols.map(s=>'_'+s).join('\n')+'\n':'{ global: '+symbols.join('; ')+'; local: *; };\n');
run(cc,[...flags,'-fvisibility=hidden','-std=c11','-D_POSIX_C_SOURCE=200809L','-Wall','-Wextra','-Werror','-I'+join(root,'native/include'),'-I'+join(pg,'src/interfaces/libpq'),'-I'+join(pg,'src/include'),'-I'+join(build,'src/include'),...(mac?['-dynamiclib','-Wl,-install_name,@rpath/'+basename(library),'-Wl,-undefined,dynamic_lookup','-Wl,-exported_symbols_list,'+exports]:['-shared','-Wl,-soname,'+basename(library),'-Wl,--version-script='+exports,'-Wl,-rpath,$ORIGIN']),join(root,'native/src/adapter.c'),...['src/interfaces/libpq/libpq.a','src/common/libpgcommon_shlib.a','src/port/libpgport_shlib.a'].map(file=>join(build,file)),join(tls,'lib/libssl.a'),join(tls,'lib/libcrypto.a'),'-pthread',...(mac?[]:['-ldl','-lm']),'-o',target]);
copyFileSync(join(pg,'COPYRIGHT'),join(out,'licenses/postgresql.txt'));copyFileSync(join(openssl,'LICENSE.txt'),join(out,'licenses/openssl.txt'));copyFileSync(join(root,'LICENSE'),join(out,'licenses/august-adapter.txt'));copyFileSync(join(root,'THIRD_PARTY_NOTICES.md'),join(out,'THIRD_PARTY_NOTICES.md'));
const inspection=mac?run('/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool',['-L',target]):run('readelf',['-d',target]);
if(mac){for(const line of inspection.split('\n').slice(1).filter(Boolean)){const file=line.trim().split(' ')[0];if(!file.startsWith('@rpath/libaug_postgres.')&&!file.startsWith('/usr/lib/')&&!file.startsWith('/System/Library/'))throw Error('Unpackaged runtime dependency '+file);}}
else{for(const match of inspection.matchAll(/Shared library: \[([^\]]+)\]/g))if(!['libc.so.6','libm.so.6','libdl.so.2','libpthread.so.0','librt.so.1'].includes(match[1]))throw Error('Unpackaged dependency '+match[1]);for(const match of run('readelf',['--version-info',target]).matchAll(/\bGLIBC_(\d+)\.(\d+)\b/g))if(+match[1]>2||+match[1]===2&&+match[2]>36)throw Error('Requires newer glibc than 2.36');}
writeFileSync(join(out,'runtime-files.json'),JSON.stringify({format:1,files:[{path:library,sha256:sha(readFileSync(target)),inspection}]},null,2)+'\n');
const source=nativeSourceIdentity(root);writeFileSync(join(out,'provenance.json'),JSON.stringify({format:1,source,target:triple,inputs:lock,compiler:run(cc,['--version']).trim(),runtimeInspection:'runtime-files.json'},null,2)+'\n');writeFileSync(join(out,'sbom.json'),JSON.stringify({format:1,components:lock.inputs,licenses:readdirSync(join(out,'licenses'))},null,2)+'\n');
const files={};let unpacked=0;const walk=(folder,prefix='')=>{for(const entry of readdirSync(folder,{withFileTypes:true})){const path=prefix+entry.name;if(entry.isDirectory())walk(join(folder,entry.name),path+'/');else{const bytes=readFileSync(join(folder,entry.name));files[path]=sha(bytes);unpacked+=bytes.length;}}};walk(out);writeFileSync(join(out,'files.json'),JSON.stringify({format:1,files},null,2)+'\n');unpacked+=readFileSync(join(out,'files.json')).length;
const archive=join(cache,'native-'+id+'.tar.gz');run('tar',['-czf',archive,'-C',out,...readdirSync(out).sort()],{env:{...process.env,COPYFILE_DISABLE:'1'}});
const artifact={id,target:{triple,os:mac?'macos':'linux',arch,...(mac?{minimumOS:'14.0',libc:'libSystem'}:{minimumLibc:'2.36',libc:'glibc'}),cpuBaseline:arch==='arm64'?'armv8-a':'x86-64'},url:'https://github.com/GreenPandaStudios/aug-postgres/releases/download/v'+manifest.version+'/native-'+id+'.tar.gz',sha256:sha(readFileSync(archive)),maximumDownloadBytes:readFileSync(archive).length,maximumUnpackedBytes:unpacked,link:{kind:'dynamic',libraries:[library]},runtime:{files:[library],closureManifest:'runtime-files.json',relocation:'loader-relative'},components:[{id:'https://github.com/postgres/postgres',version:'18.6',compatibilityKey:'aug-postgres-libpq',linkage:'static',required:true},{id:'https://github.com/openssl/openssl',version:'3.5.9',compatibilityKey:'aug-postgres-tls',linkage:'static',required:true}],fileManifest:'files.json',provenance:'provenance.json',notices:'THIRD_PARTY_NOTICES.md'};
manifest.native.artifacts=manifest.native.artifacts.filter(a=>a.id!==id).concat(artifact).sort((a,b)=>a.id.localeCompare(b.id));writeFileSync(join(root,'aug-package.json'),JSON.stringify(manifest,null,2)+'\n');writeFileSync(join(cache,'candidate.json'),JSON.stringify({source,package:manifest.name,version:manifest.version,artifact},null,2)+'\n');console.log(JSON.stringify({archive,target:triple,sha256:artifact.sha256}));
